baseURL = 'https://rohitshetty.github.io'
languageCode = 'en-us'
title = '$ls /me/'

theme = 'hugo-journal'

[params]
  description = "Journal about projects and ideas, mainly for myself"
  githubUsername = "rohitshetty"
  tagline = "Journal about work, not work, projects, coffee and everything else"
[params.work]
  jobTitle = "Developer"
  company = "Beneath A Tree"
  companyUrl = "https://beneathatree.com/"