baseURL = 'https://blog.kernelanxiety.dev'
languageCode = 'en-us'
title = '$ls /home/rohit/'
timeout = 60000 # This is required for larger galleries to be build (60 sec)
theme = [ 'hugo-shortcode-gallery','hugo-journal']
[author]
  name = "Rohit"
[params]
  description = "Journal about projects and ideas, mainly for myself"
  githubUsername = "rohitshetty"
  tagline = "Journal about work, not work, projects, coffee and everything else"
[params.work]
  jobTitle = "Developer"
  company = "Beneath A Tree Consultancy"
  companyUrl = "https://beneathatree.com/"
[params.work2]
  jobTitle = "Maker"
  company = "Beneath A Tree Learning"
  companyUrl = "https://bat.school/"

[module]
[[module.imports]]
  path="hugo-shortcode-gallery"